# import os
# import numpy as np
# import librosa as lr
# import pandas as pd
# import keras
# import pickle
# import keras.initializers
# import tensorflow as tf
# import matplotlib.pyplot as plt
# import seaborn as sns

# from tqdm import tqdm
# from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
# from keras.models import Sequential
# from keras.regularizers import l2
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import recall_score, precision_score, accuracy_score
# from sklearn.metrics import confusion_matrix, f1_score, classification_report
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# import os, os.path
# from pydub import AudioSegment
# from tqdm import tqdm

name: instrument-ml
dependencies:
  - numpy
  - librosa
  - pandas
  - keras
  - pickle
  - tensorflow
  - matplotlib
  - seaborn
  - tqdm
  - pydub